# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e25ee55e2626751e58377e5aa85beeb811905bf56ee3235915bc6dcc97e12724b339884e1361812ed9869c29756f35647b5b1f29af66de0762c7797efbf8695

test:
  secret_key_base: fcb0f909f15f5c5472abf21840d81546596201e7afc99e316ddf693346f35eb87c3cbb2228b5ebf1641bf2358aabd8b1b5a76374eabf297f1bcf42eff596e420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
